/* eslint-disable @typescript-eslint/naming-convention */

export const assets = {
    images: {
        'game/1.png': require('../assets/images/game/1.png').default,
        'game/10.png': require('../assets/images/game/10.png').default,
        'game/11.png': require('../assets/images/game/11.png').default,
        'game/12.png': require('../assets/images/game/12.png').default,
        'game/13.png': require('../assets/images/game/13.png').default,
        'game/14.png': require('../assets/images/game/14.png').default,
        'game/2.png': require('../assets/images/game/2.png').default,
        'game/3.png': require('../assets/images/game/3.png').default,
        'game/4.png': require('../assets/images/game/4.png').default,
        'game/5.png': require('../assets/images/game/5.png').default,
        'game/6.png': require('../assets/images/game/6.png').default,
        'game/7.png': require('../assets/images/game/7.png').default,
        'game/8.png': require('../assets/images/game/8.png').default,
        'game/9.png': require('../assets/images/game/9.png').default,
        'game/A.png': require('../assets/images/game/A.png').default,
        'game/C.png': require('../assets/images/game/C.png').default,
        'game/E.png': require('../assets/images/game/E.png').default,
        'game/F.png': require('../assets/images/game/F.png').default,
        'game/G.png': require('../assets/images/game/G.png').default,
        'game/I.png': require('../assets/images/game/I.png').default,
        'game/L.png': require('../assets/images/game/L.png').default,
        'game/M.png': require('../assets/images/game/M.png').default,
        'game/N.png': require('../assets/images/game/N.png').default,
        'game/O.png': require('../assets/images/game/O.png').default,
        'game/R.png': require('../assets/images/game/R.png').default,
        'game/T.png': require('../assets/images/game/T.png').default,
        'game/U.png': require('../assets/images/game/U.png').default,
        'game/Y.png': require('../assets/images/game/Y.png').default,
        'game/backspace.png': require('../assets/images/game/backspace.png').default,
        'game/backspace_bkg.png': require('../assets/images/game/backspace_bkg.png').default,
        'game/bottomBkg.png': require('../assets/images/game/bottomBkg.png').default,
        'game/enter.png': require('../assets/images/game/enter.png').default,
        'game/enter_bkg.png': require('../assets/images/game/enter_bkg.png').default,
        'game/hand.png': require('../assets/images/game/hand.png').default,
        'game/key_bkg.png': require('../assets/images/game/key_bkg.png').default,
        'game/keyboard_bkg.jpg': require('../assets/images/game/keyboard_bkg.jpg').default,
        'game/line.png': require('../assets/images/game/line.png').default,
        'game/sharpie.png': require('../assets/images/game/sharpie.png').default,
        'game/space_bkg.png': require('../assets/images/game/space_bkg.png').default,
    },
    particles: {},
    sounds: {},
    spines: {},
    atlases: {},
};

export const Images = {
    'game/1': 'game/1.png',
    'game/10': 'game/10.png',
    'game/11': 'game/11.png',
    'game/12': 'game/12.png',
    'game/13': 'game/13.png',
    'game/14': 'game/14.png',
    'game/2': 'game/2.png',
    'game/3': 'game/3.png',
    'game/4': 'game/4.png',
    'game/5': 'game/5.png',
    'game/6': 'game/6.png',
    'game/7': 'game/7.png',
    'game/8': 'game/8.png',
    'game/9': 'game/9.png',
    'game/A': 'game/A.png',
    'game/C': 'game/C.png',
    'game/E': 'game/E.png',
    'game/F': 'game/F.png',
    'game/G': 'game/G.png',
    'game/I': 'game/I.png',
    'game/L': 'game/L.png',
    'game/M': 'game/M.png',
    'game/N': 'game/N.png',
    'game/O': 'game/O.png',
    'game/R': 'game/R.png',
    'game/T': 'game/T.png',
    'game/U': 'game/U.png',
    'game/Y': 'game/Y.png',
    'game/backspace': 'game/backspace.png',
    'game/backspace_bkg': 'game/backspace_bkg.png',
    'game/bottomBkg': 'game/bottomBkg.png',
    'game/enter': 'game/enter.png',
    'game/enter_bkg': 'game/enter_bkg.png',
    'game/hand': 'game/hand.png',
    'game/key_bkg': 'game/key_bkg.png',
    'game/keyboard_bkg': 'game/keyboard_bkg.jpg',
    'game/line': 'game/line.png',
    'game/sharpie': 'game/sharpie.png',
    'game/space_bkg': 'game/space_bkg.png',
};

export const Sounds = {};

export const Particles = {};

export const Spines = {};
