/* eslint-disable @typescript-eslint/naming-convention */

export const assets = {
    images: {
        'game/bitcoin.png': require('../assets/images/game/bitcoin.png').default,
        'game/bitcoin_clicked.png': require('../assets/images/game/bitcoin_clicked.png').default,
        'game/bkg.png': require('../assets/images/game/bkg.png').default,
        'game/bubble.png': require('../assets/images/game/bubble.png').default,
        'game/bubble_text.png': require('../assets/images/game/bubble_text.png').default,
        'game/burger.png': require('../assets/images/game/burger.png').default,
        'game/burger_clicked.png': require('../assets/images/game/burger_clicked.png').default,
        'game/car.png': require('../assets/images/game/car.png').default,
        'game/crypto_wallet.png': require('../assets/images/game/crypto_wallet.png').default,
        'game/crypto_wallet_clicked.png': require('../assets/images/game/crypto_wallet_clicked.png').default,
        'game/eth.png': require('../assets/images/game/eth.png').default,
        'game/eth_clicked.png': require('../assets/images/game/eth_clicked.png').default,
        'game/fail.png': require('../assets/images/game/fail.png').default,
        'game/hand.png': require('../assets/images/game/hand.png').default,
        'game/mining_farm.png': require('../assets/images/game/mining_farm.png').default,
        'game/mining_farm_clicked.png': require('../assets/images/game/mining_farm_clicked.png').default,
        'game/money_bar.png': require('../assets/images/game/money_bar.png').default,
        'game/nft.png': require('../assets/images/game/nft.png').default,
        'game/nft_clicked.png': require('../assets/images/game/nft_clicked.png').default,
        'game/phone.png': require('../assets/images/game/phone.png').default,
        'game/rolex.png': require('../assets/images/game/rolex.png').default,
        'game/rolex_clicked.png': require('../assets/images/game/rolex_clicked.png').default,
        'game/try_again.png': require('../assets/images/game/try_again.png').default,
        'game/yacht.png': require('../assets/images/game/yacht.png').default,
        'game/yacht_clicked.png': require('../assets/images/game/yacht_clicked.png').default,
        'house/gf.png': require('../assets/images/house/gf.png').default,
        'house/house.png': require('../assets/images/house/house.png').default,
        'house/layer1.png': require('../assets/images/house/layer1.png').default,
        'house/layer2.png': require('../assets/images/house/layer2.png').default,
        'house/layer3.png': require('../assets/images/house/layer3.png').default,
        'house/layer4.png': require('../assets/images/house/layer4.png').default,
        'house/layer5.png': require('../assets/images/house/layer5.png').default,
        'house/layer6.png': require('../assets/images/house/layer6.png').default,
        'house/layer7.png': require('../assets/images/house/layer7.png').default,
        'house/layer8.png': require('../assets/images/house/layer8.png').default,
        'house/layer9.png': require('../assets/images/house/layer9.png').default,
        'main_guy/brows.png': require('../assets/images/main_guy/brows.png').default,
        'main_guy/brows_happy.png': require('../assets/images/main_guy/brows_happy.png').default,
        'main_guy/eyes_closed.png': require('../assets/images/main_guy/eyes_closed.png').default,
        'main_guy/eyes_down.png': require('../assets/images/main_guy/eyes_down.png').default,
        'main_guy/eyes_happy.png': require('../assets/images/main_guy/eyes_happy.png').default,
        'main_guy/head.png': require('../assets/images/main_guy/head.png').default,
        'main_guy/left_arm.png': require('../assets/images/main_guy/left_arm.png').default,
        'main_guy/left_leg.png': require('../assets/images/main_guy/left_leg.png').default,
        'main_guy/lips.png': require('../assets/images/main_guy/lips.png').default,
        'main_guy/mouth_1.png': require('../assets/images/main_guy/mouth_1.png').default,
        'main_guy/mouth_2.png': require('../assets/images/main_guy/mouth_2.png').default,
        'main_guy/mouth_3.png': require('../assets/images/main_guy/mouth_3.png').default,
        'main_guy/right_arm.png': require('../assets/images/main_guy/right_arm.png').default,
        'main_guy/right_leg.png': require('../assets/images/main_guy/right_leg.png').default,
        'main_guy/torso.png': require('../assets/images/main_guy/torso.png').default,
        'poor/body.png': require('../assets/images/poor/body.png').default,
        'poor/close_eyes.png': require('../assets/images/poor/close_eyes.png').default,
        'poor/eye l_lookdown.png': require('../assets/images/poor/eye l_lookdown.png').default,
        'poor/eye r_lookdown.png': require('../assets/images/poor/eye r_lookdown.png').default,
        'poor/eyes_happy.png': require('../assets/images/poor/eyes_happy.png').default,
        'poor/eyes_look_down.png': require('../assets/images/poor/eyes_look_down.png').default,
        'poor/head.png': require('../assets/images/poor/head.png').default,
        'poor/l_arm.png': require('../assets/images/poor/l_arm.png').default,
        'poor/l_arm_phone.png': require('../assets/images/poor/l_arm_phone.png').default,
        'poor/l_leg.png': require('../assets/images/poor/l_leg.png').default,
        'poor/lips.png': require('../assets/images/poor/lips.png').default,
        'poor/mouth.png': require('../assets/images/poor/mouth.png').default,
        'poor/r_leg.png': require('../assets/images/poor/r_leg.png').default,
    },
    particles: {},
    sounds: {},
    spines: {},
    atlases: {},
};

export const Images = {
    'game/bitcoin': 'game/bitcoin.png',
    'game/bitcoin_clicked': 'game/bitcoin_clicked.png',
    'game/bkg': 'game/bkg.png',
    'game/bubble': 'game/bubble.png',
    'game/bubble_text': 'game/bubble_text.png',
    'game/burger': 'game/burger.png',
    'game/burger_clicked': 'game/burger_clicked.png',
    'game/car': 'game/car.png',
    'game/crypto_wallet': 'game/crypto_wallet.png',
    'game/crypto_wallet_clicked': 'game/crypto_wallet_clicked.png',
    'game/eth': 'game/eth.png',
    'game/eth_clicked': 'game/eth_clicked.png',
    'game/fail': 'game/fail.png',
    'game/hand': 'game/hand.png',
    'game/mining_farm': 'game/mining_farm.png',
    'game/mining_farm_clicked': 'game/mining_farm_clicked.png',
    'game/money_bar': 'game/money_bar.png',
    'game/nft': 'game/nft.png',
    'game/nft_clicked': 'game/nft_clicked.png',
    'game/phone': 'game/phone.png',
    'game/rolex': 'game/rolex.png',
    'game/rolex_clicked': 'game/rolex_clicked.png',
    'game/try_again': 'game/try_again.png',
    'game/yacht': 'game/yacht.png',
    'game/yacht_clicked': 'game/yacht_clicked.png',
    'house/gf': 'house/gf.png',
    'house/house': 'house/house.png',
    'house/layer1': 'house/layer1.png',
    'house/layer2': 'house/layer2.png',
    'house/layer3': 'house/layer3.png',
    'house/layer4': 'house/layer4.png',
    'house/layer5': 'house/layer5.png',
    'house/layer6': 'house/layer6.png',
    'house/layer7': 'house/layer7.png',
    'house/layer8': 'house/layer8.png',
    'house/layer9': 'house/layer9.png',
    'main_guy/brows': 'main_guy/brows.png',
    'main_guy/brows_happy': 'main_guy/brows_happy.png',
    'main_guy/eyes_closed': 'main_guy/eyes_closed.png',
    'main_guy/eyes_down': 'main_guy/eyes_down.png',
    'main_guy/eyes_happy': 'main_guy/eyes_happy.png',
    'main_guy/head': 'main_guy/head.png',
    'main_guy/left_arm': 'main_guy/left_arm.png',
    'main_guy/left_leg': 'main_guy/left_leg.png',
    'main_guy/lips': 'main_guy/lips.png',
    'main_guy/mouth_1': 'main_guy/mouth_1.png',
    'main_guy/mouth_2': 'main_guy/mouth_2.png',
    'main_guy/mouth_3': 'main_guy/mouth_3.png',
    'main_guy/right_arm': 'main_guy/right_arm.png',
    'main_guy/right_leg': 'main_guy/right_leg.png',
    'main_guy/torso': 'main_guy/torso.png',
    'poor/body': 'poor/body.png',
    'poor/close_eyes': 'poor/close_eyes.png',
    'poor/eye l_lookdown': 'poor/eye l_lookdown.png',
    'poor/eye r_lookdown': 'poor/eye r_lookdown.png',
    'poor/eyes_happy': 'poor/eyes_happy.png',
    'poor/eyes_look_down': 'poor/eyes_look_down.png',
    'poor/head': 'poor/head.png',
    'poor/l_arm': 'poor/l_arm.png',
    'poor/l_arm_phone': 'poor/l_arm_phone.png',
    'poor/l_leg': 'poor/l_leg.png',
    'poor/lips': 'poor/lips.png',
    'poor/mouth': 'poor/mouth.png',
    'poor/r_leg': 'poor/r_leg.png',
};

export const Sounds = {};

export const Particles = {};

export const Spines = {};
